SDT-TIME-STAMP-1.0
1714651533 C:\Documents and Settings\Firma\Escritorio\aloha_n_procesos\aloha.ssy
1714651533 C:\Documents and Settings\Firma\Escritorio\aloha_n_procesos\Sistema_aloha.sbk
1714651533 C:\Documents and Settings\Firma\Escritorio\aloha_n_procesos\Emisor.spr
1714651533 C:\Documents and Settings\Firma\Escritorio\aloha_n_procesos\Usuario.spr
1714651533 C:\Documents and Settings\Firma\Escritorio\aloha_n_procesos\Canal.spr
1714651533 C:\Documents and Settings\Firma\Escritorio\aloha_n_procesos\Emitir_TICs.spd
1714651533 C:\Documents and Settings\Firma\Escritorio\aloha_n_procesos\Leer_Intencion.spd
1714651533 C:\Documents and Settings\Firma\Escritorio\aloha_n_procesos\Emitir_Colision.spd
